name: test error

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**

jobs:
  setup-chrome-rd:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Chrome
        run: |
          Invoke-WebRequest -Uri "https://dl.google.com/chrome/install/standalonesetup64.exe" -OutFile "chrome_setup.exe"
          Start-Process "chrome_setup.exe" -ArgumentList "/silent /install" -Wait

      - name: Install Chrome Remote Desktop
        run: |
          Invoke-WebRequest -Uri "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile "chrome_remote_desktop_host.msi"
          Start-Process "msiexec.exe" -ArgumentList "/i", "chrome_remote_desktop_host.msi", "/quiet" -Wait

      - name: Start Chrome Remote Desktop Host
        run: |
         & "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="4/0AUJR-x6lQdenPGsaCbsi-WEr0O-WDWeQJ7z5W1WUR5Ric6E1_w-xE3fCu_7f-HMnvqV9WA" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME   --pin=111111
      - name: Wait
        run: Start-Sleep -Seconds 2147483
 
